# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -, make sure they open in the same path
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# open new windows in the current path
bind c new-window -c "#{pane_current_path}"

# reload config file
bind r source-file ~/.config/tmux/tmux.conf

# we want to integrate to native clipboard
set -g set-clipboard on

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# DESIGN TWEAKS
set -ga terminal-overrides ",xterm-256color"
set -s extended-keys always
set -as terminal-features ',kitty:extkeys:RGB'
set -g allow-passthrough on
bind-key -n S-Enter send-keys Escape "[13;2u"

# loud or quiet?
set -g visual-activity on
set -g visual-bell on
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Enable more natural mouse scrolling
set -g mouse on

# panes
set -g pane-border-style 'fg=colour238'
set -g pane-active-border-style 'fg=yellow,bold'
set -g pane-border-lines heavy
set -g pane-border-status off
set -g pane-border-format ' #{pane_index}: #{pane_current_command} '
set -g pane-border-indicators 'both'
set-hook -g window-layout-changed 'if -F "#{==:#{window_panes},1}" "set-window-option pane-border-status off" "set-window-option pane-border-status top"'

# saner pane numbering
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1
